name: "Configure makepkg"
runs:
  using: "composite"
  steps:
    - shell: bash -e {0}
      run: |
        sed -e "s/#\?MAKEFLAGS=.*/MAKEFLAGS=-j$(nproc)/" -i /etc/makepkg.conf
        dbus-uuidgen --ensure=/etc/machine-id || dbus-uuidgen > /etc/machine-id
        mkdir -p makepkg
        useradd -g wheel -d $(realpath makepkg) -m makepkg
        echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
        chown -R makepkg:root repository makepkg
