github:
  repository: username/repository
  keyring: username/keyring
  mirrorlist: username/mirrorlist
  cactus: username/cactus
  token: github_token
pacman:
  repository: repository
  archs: x86_64 aarch64
database:
  ENGINE: django.db.backends.mysql
  HOST: example.com
  PORT: 3306
  NAME: database_name
  USER: username
  PASSWORD: password
scheduler:
  default: GitHubActions
  GitHubActions:
    total: 15
  x86_64:
    total: 1
  aarch64:
    total: 1
publisher:
  host: example.com
  port: port
  user: username
  path: /path/to/repository
