name: "Upgrade archlinux"
inputs:
  arch:
    description: 'Architecture'
    required: false
    default: 'x86_64'
outputs:
  time:
    description: "Current time"
    value: ${{ steps.time.outputs.time }}
runs:
  using: "composite"
  steps:
    - name: Get time
      id: time
      shell: bash -e {0}
      run: echo "time=$(date +%F-%T)" >> $GITHUB_OUTPUT

    - name: Set up pacman package cache
      uses: actions/cache@master
      with:
        path: /var/cache/pacman/pkg
        key: pacman-package-${{ inputs.arch }}-${{ steps.time.outputs.time }}
        restore-keys: pacman-package-${{ inputs.arch }}-

    - name: Generate default secret key
      shell: bash -e {0}
      run: pacman-key --init

    - name: Disable the default sandbox
      shell: bash -e {0}
      run: |
        # See https://github.com/arch4edu/cactus/issues/10
        sed 's/^#DisableSandbox/DisableSandbox/' -i /etc/pacman.conf || :
        sed 's/^DownloadUser/#DownloadUser/' -i /etc/pacman.conf || :

    - name: Upgrade the system
      shell: bash -e {0}
      run: pacman -Syu --noconfirm

    - name: Cleanup pacman cache
      uses: webiny/action-post-run@3.1.0
      with:
        run: pacman -Sc --noconfirm
