name: "Upload build log"
inputs:
  pkgbase:
    description: 'pkgbase'
    required: true
runs:
  using: "composite"
  steps:
    - id: basename
      if: ${{ always() }}
      shell: bash -e {0}
      run: echo "::set-output name=basename::$(basename ${{ inputs.pkgbase }})"

    - uses: actions/upload-artifact@master
      if: ${{ always() }}
      with:
        name: ${{ steps.basename.outputs.basename }}.log
        path: repository/${{ inputs.pkgbase }}/build.log
