name: "Configure pacman repository"
inputs:
  pacman-repository:
    description: 'Name of the pacman repository'
    required: true
  keyring-repository:
    description: 'Keyring repository'
    required: true
  mirrorlist-repository:
    description: 'Mirrorlist repository'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@main
      with:
        repository: ${{ inputs.keyring-repository }}
        path: keyring

    - uses: actions/checkout@main
      with:
        repository: ${{ inputs.mirrorlist-repository }}
        path: mirrorlist

    - shell: bash -e {0}
      run: |
        cp keyring/* /usr/share/pacman/keyrings/
        pacman-key --init
        pacman-key --populate ${{ inputs.pacman-repository }}
        echo [options] >> /etc/pacman.conf
        echo [${{ inputs.pacman-repository }}] >> /etc/pacman.conf
        echo Include = /etc/pacman.d/mirrorlist.${{ inputs.pacman-repository }} >> /etc/pacman.conf
        sed 's/^#DisableSandbox/DisableSandbox/' -i /etc/pacman.conf || :
        sed 's/#//' -i mirrorlist/*mirrorlist*
        rankmirrors -r ${{ inputs.pacman-repository }} mirrorlist/*mirrorlist* | sed -n '/^#/b;p' | tee /etc/pacman.d/mirrorlist.${{ inputs.pacman-repository }}
        pacman -Sy
