name: "Configure pacman repository"
inputs:
  pacman-repository:
    description: 'Name of the pacman repository'
    required: true
  keyring-repository:
    description: 'Keyring repository'
    required: true
  mirrorlist-repository:
    description: 'Mirrorlist repository'
    required: true
outputs:
  time:
    description: "Current time"
    value: ${{ steps.time.outputs.time }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@master
      with:
        repository: ${{ inputs.keyring-repository }}
        path: pacman/keyring

    - uses: actions/checkout@master
      with:
        repository: ${{ inputs.mirrorlist-repository }}
        path: pacman/mirrorlist

    - shell: bash -e {0}
      run: |
        mkdir -p pacman/db
        cd pacman
        cp keyring/* /usr/share/pacman/keyrings/
        pacman-key --gpgdir gnupg --init
        pacman-key --gpgdir gnupg --populate ${{ inputs.pacman-repository }}
        echo [options] > pacman.conf
        pacman-conf | grep '^Architecture' >> pacman.conf
        echo [${{ inputs.pacman-repository }}] >> pacman.conf
        sed 's/#//' mirrorlist/*mirrorlist* >> pacman.conf
        pacman -Sy --config pacman.conf --dbpath db
