DatabaseDirectory /var/lib/clamav
LocalSocket /run/clamav/clamd.sock
PidFile /run/clamav/clamd.pid
LogFile /tmp/clamd.log
User root
MaxThreads 10
MaxScanSize 4000000000
MaxFileSize 2000000000
MaxRecursion 32
MaxQueue 200
TemporaryDirectory /tmp
