name: "Remove unwanted software in ubuntu-latest"
inputs:
  root:
    description: 'root where ubuntu is mounted'
    required: false
    default: '/ubuntu'
runs:
  using: "composite"
  steps:
    - shell: bash -e {0}
      run: |
        df -h

        arch-chroot ${{ inputs.root }} apt-get autoremove -y \
          gcc g++ gcc-{9,10,11,12,13} g++-{9,10,11,12,13} \
          llvm-{13,14,15} clang-{13,14,15} clang-format-{13,14,15} \
          dotnet-sdk-{6,7,8}.0 mono-complete \
          java-common temurin-{8,11,17,21}-jdk \
          php8.1\* ruby \
          mysql-client mysql-server \
          google-cloud-cli azure-cli \
          microsoft-edge-stable google-chrome-stable firefox

        cd ${{ inputs.root }}

        for i in usr/local/lib/android opt/hostedtoolcache/CodeQL
        do
          [ ! -d $i ] && continue
          du -sh $i
          rm -r $i
        done

        df -h

    - uses: webiny/action-post-run@3.1.0
      with:
        run: sh -c "arch-chroot ${{ inputs.root }} dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n"
