name: Trigger rebuild (JS)

run-name: Trigger rebuild (JS) for ${{ inputs.pkgbase }}

on:
  workflow_dispatch:
    inputs:
      pkgbase:
        description: 'Path to pkgbase (space-separated for multiple, e.g., x86_64/pkg1 x86_64/pkg2)'
        required: true

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      CACTUS_CONFIG: ${{ secrets.CACTUS_CONFIG }}

    steps:
      - name: Update status (JS)
        uses: arch4edu/cactus/actions/update-status-js@main
        with:
          pkgbase: ${{ github.event.inputs.pkgbase }}
          status: stale
          workflow: ${{ github.run_id }}